### ISSUE TITLE
Incorrect documentation of the length of the machine-independent format?

### ISSUE THREAD

**Issue by favonia** [backtracking/bitv#26]
I believe the following documentation for the machine-independent format is incorrect:
https://github.com/backtracking/bitv/blob/531844cb50b8639342310989c055eb274f73e428/bitv.mli#L204-L206
The reason is that the code seems to fix the number of bytes to `8`. If so, the length is _always_ **8+ceil(n/8)**.
https://github.com/backtracking/bitv/blob/531844cb50b8639342310989c055eb274f73e428/bitv.ml#L582-L583
I wonder if I missed anything?

**Comment by backtracking** [comment]
You're right. I'm fixing the documentation.
