### ISSUE TITLE
What is the correct way to buffer bits ?

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/bitv#3]
Is there something like the stdlib's Buffer module to accumulate many bits
before finally storing them on disk ?
Later, I'd like to read them back in of course.

**Comment by backtracking** [comment]
Hi François,

There is no problem in marshalling bit vectors to/from disk, since they
are only arrays of integers.

But there is currently no such thing as a bit buffer i.e. a resizeable
array of bits. Note that one would have to choose whether bit vectors
are extended on least or most significant bit side. Out of curiosity,
which way are you interested in?

--
Jean-Christophe

**Comment by UnixJunkie** [comment]
I am interested into adding more bits to the right (just like with a string buffer in fact), maybe it is the least significant bit side ?

**Comment by UnixJunkie** [comment]
I will test it soon, thanks !

**Comment by backtracking** [comment]
The question is relevant when we turn the bit buffer into a bit vector.
So I rephrase my question: when we do so, do you want the bit that were
added last to be the most or the least significant? The former is easier
to implement.

--
Jean-Christophe

**Comment by UnixJunkie** [comment]
I don't know, but maybe I'm stupid.
Is there a way to downsize a bit vector ?
Let's say that I created a sufficiently large one but at the end of my computation I detect it is too big:
I'd like to resize it down before dumping it to disk.
Of course, I'd like to avoid a whole copy of the bitv I would like to resize.

**Comment by backtracking** [comment]
> I don't know, but maybe I'm stupid.
> Is there a way to downsize a bit vector ?

You can do this with Bitv.sub but it returns a new bit vector, and thus
it will make a copy.

But, assuming we implement bit buffers, turning a bit buffer into a bit
vector will also make a copy (as with Buffer.contents, for instance).

-- 
Jean-Christophe

**Comment by UnixJunkie** [comment]
I will use Bitv.sub then.
