### ISSUE TITLE
Integer overflow in fill, blit, and sub

### ISSUE THREAD

**Issue by nikolaushuber** [backtracking/bitv#31]
Using `Bitv.fill`, `Bitv.blit`, or `Bitv.sub` with very big integers can lead to a segmentation fault, whereas the corresponding methods from the `Array` module correctly raise an `Invalid_argument` exception. This is due to an integer overflow in the guarding if expression in the respective methods. I have an adapted version [here](https://github.com/nikolaushuber/bitv/tree/fill-overflow) which I can make into a PR if wanted. 

This was discovered by annotating the interface of `Bitv` with [Gospel](https://github.com/ocaml-gospel/gospel) annotations, and using [ortac/qcheck-stm](https://github.com/ocaml-gospel/ortac) to perform randomised testing. The contracts can be seen [in this branch](https://github.com/nikolaushuber/bitv/tree/gospel-spec), the output of `ortac` is visible under the GitHub Actions tab. 

This utilises a [pinned version](https://github.com/nikolaushuber/ortac/tree/fork-prop) of ortac, as it uses some features not yet upstreamed to the main repository.

**Comment by backtracking** [comment]
Thanks @nikolaushuber for reporting this issue!
Indeed, I can see that `Array` is carefully using subtractions instead of additions to make theses checks.
If you can make a PR with such a fix, I'll be happy to merge it (and that would credit you for the fix).
