### ISSUE TITLE
Inconsistent behaviour with zero-length vectors

### ISSUE THREAD

**Issue by nikolaushuber** [backtracking/bitv#33]
When trying to rotate a zero-length bit-vector with `rotatel` or `rotater`, a `Division_by_zero` error is raised. However, a zero-length bit-vector can successfully be shifted by `shiftl` and `shiftr`.

The exception seems to come from the `mod` operations [here](https://github.com/backtracking/bitv/blob/94ac6c6828186d8cdd2fd96ce16c47cad43378ad/bitv.ml#L424) and [here](https://github.com/backtracking/bitv/blob/94ac6c6828186d8cdd2fd96ce16c47cad43378ad/bitv.ml#L409).

For consistency, `rotater` and `rotatel` should potentially use `copy` in case of zero-length vectors as well. If wanted, I can prepare a PR for this issue.

This inconsistency has been found with [ortac](https://github.com/ocaml-gospel/ortac).

**Comment by backtracking** [comment]
Thanks for reporting this! (I'm glad to see that `ortac` is used and useful!)
