### ISSUE TITLE
having an opam.in instead of an opam file makes it non opam pinnable

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/bitv#7]
if the repository doesn't contain an opam file; then it cannot be pinned with opam

**Comment by UnixJunkie** [comment]
the fix is to remove the version field in the opam.in file (since this field is not needed by newer versions of opam) and rename the file back to opam

**Comment by UnixJunkie** [comment]
this is still not fixed. :(

**Comment by backtracking** [comment]
I've renamed opam.in into opam.
