### ISSUE TITLE
.cmt and .cmti files are not installed for bitv with opam

### ISSUE THREAD

**Issue by UnixJunkie** [backtracking/bitv#9]
So, the ocamldoc doesn't show up in ocp-browser when I type 'Bitv.create' then hit the spacebar.
Also, this will prevent Bitv from being indexed by the soon to come Hoogle for OCaml service.

**Comment by UnixJunkie** [comment]
If you are interested, I might have a solution to that.

**Comment by UnixJunkie** [comment]
OK, the problem is slightly bigger: there is no ocamldoc for each function...

**Comment by backtracking** [comment]
Indeed. It is currently (lightly) documented using ocamlweb.

**Comment by UnixJunkie** [comment]
are you interested if the documentation is converted to ocamldoc?

**Comment by backtracking** [comment]
Moved to odoc just now.
